apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
        - name: todoapp
          image: todoapp:v1
          # Use the locally‑built image if present; don’t try to pull from DockerHub
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
